# Generated by Django 5.0 on 2023-12-20 16:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('area_code', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('may_contact', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('contact_method', models.CharField(choices=[('tel', 'Telephone'), ('email', 'Email')], max_length=10)),
                ('sunday_from', models.TimeField(blank=True, null=True)),
                ('sunday_to', models.TimeField(blank=True, null=True)),
                ('monday_from', models.TimeField(blank=True, null=True)),
                ('monday_to', models.TimeField(blank=True, null=True)),
                ('tuesday_from', models.TimeField(blank=True, null=True)),
                ('tuesday_to', models.TimeField(blank=True, null=True)),
                ('wenesday_from', models.TimeField(blank=True, null=True)),
                ('wenesday_to', models.TimeField(blank=True, null=True)),
                ('thursday_from', models.TimeField(blank=True, null=True)),
                ('thursday_to', models.TimeField(blank=True, null=True)),
                ('friday_from', models.TimeField(blank=True, null=True)),
                ('friday_to', models.TimeField(blank=True, null=True)),
                ('satarday_from', models.TimeField(blank=True, null=True)),
                ('satarday_to', models.TimeField(blank=True, null=True)),
                ('fitness_instruction', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('personal_training', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('nutrition', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('pysical_therapy', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('pilates_therapy', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('sports_conditioning', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('wellness_lifestyle', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('yoga', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('massage_therapy', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('martial_arts', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('athletic_training', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('experience_years', models.IntegerField()),
                ('charging_rate_currency', models.CharField(choices=[('USD', 'USD($)'), ('CAD', 'CAD')], max_length=3)),
                ('charging_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_methods_cash', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('payment_methods_cashier_check', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('payment_methods_card', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('payment_methods_personal_check', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
