# Generated by Django 5.0 on 2023-12-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerregistration',
            name='experience_years',
            field=models.CharField(max_length=10),
        ),
    ]
