# Generated by Django 5.0.1 on 2024-01-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainersignup',
            name='birth_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trainersignup',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
