# Generated by Django 5.0 on 2023-12-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainers', '0002_alter_trainerregistration_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerregistration',
            name='charging_rate',
            field=models.CharField(max_length=100),
        ),
    ]
