# Generated by Django 5.0.1 on 2024-01-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_alter_trainersignup_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainersignup',
            name='accredited_certification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainersignup',
            name='additional_certifications',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainersignup',
            name='calendar_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainersignup',
            name='education_background',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainersignup',
            name='event_preparation_specialties',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainersignup',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainersignup',
            name='preferred_training_environment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainersignup',
            name='speciality_populations',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainersignup',
            name='specialization_fitness_training',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainersignup',
            name='training_equipment_utilized',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainersignup',
            name='training_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
