# Generated by Django 5.0 on 2023-12-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainers', '0003_alter_trainerregistration_charging_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='resistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('area_code', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('may_contact', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('contact_method', models.CharField(choices=[('tel', 'Telephone'), ('email', 'Email')], max_length=10)),
                ('sunday_from', models.TimeField(blank=True, null=True)),
                ('sunday_to', models.TimeField(blank=True, null=True)),
                ('monday_from', models.TimeField(blank=True, null=True)),
                ('monday_to', models.TimeField(blank=True, null=True)),
                ('tuesday_from', models.TimeField(blank=True, null=True)),
                ('tuesday_to', models.TimeField(blank=True, null=True)),
                ('wenesday_from', models.TimeField(blank=True, null=True)),
                ('wenesday_to', models.TimeField(blank=True, null=True)),
                ('thursday_from', models.TimeField(blank=True, null=True)),
                ('thursday_to', models.TimeField(blank=True, null=True)),
                ('friday_from', models.TimeField(blank=True, null=True)),
                ('friday_to', models.TimeField(blank=True, null=True)),
                ('satarday_from', models.TimeField(blank=True, null=True)),
                ('satarday_to', models.TimeField(blank=True, null=True)),
                ('fitness_instruction', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('personal_training', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('nutrition', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('pysical_therapy', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('pilates_therapy', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('sports_conditioning', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('wellness_lifestyle', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('yoga', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('massage_therapy', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('martial_arts', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('athletic_training', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('experience_years', models.CharField(max_length=10)),
                ('charging_rate_currency', models.CharField(choices=[('USD', 'USD($)'), ('CAD', 'CAD')], max_length=3)),
                ('charging_rate', models.CharField(max_length=100)),
                ('payment_methods_cash', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('payment_methods_cashier_check', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('payment_methods_card', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('payment_methods_personal_check', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
            ],
        ),
    ]
