# Generated by Django 5.0 on 2023-12-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainers', '0004_resistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('confirm_password', models.TextField(max_length=50)),
            ],
        ),
    ]
